### PR TITLE
GAWB-778 Multiple cromwell servers in config

### PR DESCRIPTION
**Pull request by helgridly**
companion PRs in firecloud-develop for conf files:
https://github.com/broadinstitute/firecloud-develop/pull/84
https://github.com/broadinstitute/firecloud-develop/pull/85
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Make sure liquibase is updated if appropriate
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [x] Tell  that the PR exists if he wants to look at it **(apply requires_doge label)**
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- [x] **LR**: Initial review by LR and others.
- [ ] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [ ]  sign off
- [x] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Squash commits, rebase if necessary
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Merge to develop 
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: Check configuration files in Jenkins in case they need changes
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by MattPutnam** [comment]
👍

**Comment by dvoet** [comment]
👎 

I have a couple strong opinions about this and @davidangb should read this too. 
1. I don't think the HttpExecutionServiceDAO should change at all. It should be responsible for talking to 1 and only 1 cromwell. After all, we still need to be able to address a specific cromwell. Instead, we should have a cromwell registry. The registry knows about different HttpExecutionServiceDAOs. In here would be the function to get a particular HttpExecutionServiceDAO or the balanced choice.
2. We should have an identifier for a cromwell other than its address. The mapping from id to address would be in config and fed to the HttpExecutionServiceDAO registry. The id would be stored on each workflow.

**Comment by davidangb** [comment]
The id->address mapping has some complexity. Consider the use case where we want to gracefully retire a cromwell instance from use ... we'd need to keep that instance in config for as long as rawls would need to query it, at minimum for however long it takes to complete all its workflows. But we wouldn't want to send new workflows to it, so we'd need an additional flag in config for that cromwell to be read-only. I admit this use case isn't common.

I like the concept of multiple HttpExecutionServiceDAOs. I suspect implementation is going to be a bit tricky, but probably worth it.

**Comment by helgridly** [comment]
Will close and update to address Doug's comments. Not sure what the implementation will look like yet.

**Pull request closed without merging**
