### PR TITLE
adopt cromwell32 jar

### PR DESCRIPTION
**Pull request by davidangb**
DataBiosphere/firecloud-app#76

adopt the new cromwell32 jar, including an import change for compatibility.

### CODE REVIEW

**Review by jmthibault79 — APPROVED** [review]
:+1: pending perf tests

**Comment by davidangb** [comment]
whoops, sorry - latest commit to update the `cromwellVersion` hash to reflect the c32 hotfix got lost in the rebase/force-push. The hash is updated (see also broadinstitute/agora#259) but the commit message is hidden.

**Comment by davidangb** [comment]
UI automation tests had one failure:
```
[info] *** 1 TEST FAILED ***
[error] Failed: Total 124, Failed 1, Errors 0, Passed 123, Ignored 3
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec

[info] - launch workflow with input not defined *** FAILED *** (36 seconds, 210 milliseconds)
[info]   org.broadinstitute.dsde.workbench.service.RestException: {
[info]   "statusCode": 400,
[info]   "source": "FireCloud",
[info]   "timestamp": 1528052193729,
[info]   "causes": [],
[info]   "stackTrace": [],
[info]   "message": "TSV parsing error: no header"
[info] }
[info]   at org.broadinstitute.dsde.workbench.service.RestClient.throwRestException(RestClient.scala:81)
[info]   at org.broadinstitute.dsde.workbench.service.RestClient.parseResponse(RestClient.scala:76)
[info]   at org.broadinstitute.dsde.workbench.service.RestClient.parseResponse$(RestClient.scala:71)
[info]   at org.broadinstitute.dsde.workbench.service.Orchestration$.parseResponse(Orchestration.scala:515)
[info]   at org.broadinstitute.dsde.workbench.service.RestClient.postRequestWithMultipart(RestClient.scala:108)
[info]   at org.broadinstitute.dsde.workbench.service.RestClient.postRequestWithMultipart$(RestClient.scala:104)
[info]   at org.broadinstitute.dsde.workbench.service.Orchestration$.postRequestWithMultipart(Orchestration.scala:515)
[info]   at org.broadinstitute.dsde.workbench.service.Orchestration.importMetaData(Orchestration.scala:432)
[info]   at org.broadinstitute.dsde.workbench.service.Orchestration.importMetaData$(Orchestration.scala:430)
[info]   at org.broadinstitute.dsde.workbench.service.Orchestration$.importMetaData(Orchestration.scala:515)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.$anonfun$new$23(MethodLaunchSpec.scala:144)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.$anonfun$new$23$adapted(MethodLaunchSpec.scala:142)
[info]   at org.broadinstitute.dsde.workbench.fixture.WorkspaceFixtures.$anonfun$withWorkspace$1(WorkspaceFixtures.scala:40)
[info]   at scala.util.Try$.apply(Try.scala:209)
[info]   at org.broadinstitute.dsde.workbench.fixture.WorkspaceFixtures.withWorkspace(WorkspaceFixtures.scala:40)
[info]   at org.broadinstitute.dsde.workbench.fixture.WorkspaceFixtures.withWorkspace$(WorkspaceFixtures.scala:29)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.withWorkspace(MethodLaunchSpec.scala:14)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.$anonfun$new$22(MethodLaunchSpec.scala:142)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.$anonfun$new$22$adapted(MethodLaunchSpec.scala:141)
[info]   at org.broadinstitute.dsde.workbench.fixture.BillingFixtures.$anonfun$withCleanBillingProject$1(BillingFixtures.scala:151)
[info]   at scala.util.Try$.apply(Try.scala:209)
[info]   at org.broadinstitute.dsde.workbench.fixture.BillingFixtures.withCleanBillingProject(BillingFixtures.scala:151)
[info]   at org.broadinstitute.dsde.workbench.fixture.BillingFixtures.withCleanBillingProject$(BillingFixtures.scala:148)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.withCleanBillingProject(MethodLaunchSpec.scala:14)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.$anonfun$new$21(MethodLaunchSpec.scala:141)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:407)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.org$broadinstitute$dsde$workbench$service$test$CleanUp$$super$withFixture(MethodLaunchSpec.scala:14)
[info]   at org.broadinstitute.dsde.workbench.service.test.CleanUp.$anonfun$withFixture$1(CleanUp.scala:98)
[info]   at scala.util.Try$.apply(Try.scala:209)
[info]   at org.broadinstitute.dsde.workbench.service.test.CleanUp.withFixture(CleanUp.scala:98)
[info]   at org.broadinstitute.dsde.workbench.service.test.CleanUp.withFixture$(CleanUp.scala:96)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.withFixture(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.FreeSpecLike.invokeWithFixture$1(FreeSpecLike.scala:405)
[info]   at org.scalatest.FreeSpecLike.$anonfun$runTest$1(FreeSpecLike.scala:417)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FreeSpecLike.runTest(FreeSpecLike.scala:417)
[info]   at org.scalatest.FreeSpecLike.runTest$(FreeSpecLike.scala:399)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.org$scalatest$OneInstancePerTest$$super$runTest(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.OneInstancePerTest.runTest(OneInstancePerTest.scala:131)
[info]   at org.scalatest.OneInstancePerTest.runTest$(OneInstancePerTest.scala:123)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.org$scalatest$ParallelTestExecution$$super$runTest(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.ParallelTestExecution.runTest(ParallelTestExecution.scala:164)
[info]   at org.scalatest.ParallelTestExecution.runTest$(ParallelTestExecution.scala:148)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.runTest(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.OneInstancePerTest.runTests(OneInstancePerTest.scala:181)
[info]   at org.scalatest.OneInstancePerTest.runTests$(OneInstancePerTest.scala:172)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.org$scalatest$ParallelTestExecution$$super$runTests(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.ParallelTestExecution.runTests(ParallelTestExecution.scala:97)
[info]   at org.scalatest.ParallelTestExecution.runTests$(ParallelTestExecution.scala:79)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.runTests(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike.$anonfun$run$1(FreeSpecLike.scala:520)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FreeSpecLike.run(FreeSpecLike.scala:520)
[info]   at org.scalatest.FreeSpecLike.run$(FreeSpecLike.scala:519)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.org$scalatest$ParallelTestExecution$$super$run(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.ParallelTestExecution.run(ParallelTestExecution.scala:261)
[info]   at org.scalatest.ParallelTestExecution.run$(ParallelTestExecution.scala:258)
[info]   at org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec.run(MethodLaunchSpec.scala:14)
[info]   at org.scalatest.tools.DistributedTestRunnerSuite.run(DistributedTestRunnerSuite.scala:22)
[info]   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by davidangb** [comment]
in a manual run, `MethodLaunchSpec` passed:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/6558/

**Pull request merged**
