### PR TITLE
[DDO-1899] Add capability to direct statsd to an additional sidecar endpoint

### PR DESCRIPTION
**Pull request by jack-r-warren**
DevOps wants to make Rawls's statsd metrics go to both HostedGraphite and our own Prometheus at the same time ([DDO-1899](https://broadworkbench.atlassian.net/browse/DDO-1899)). We're using https://github.com/prometheus/statsd_exporter as a sidecar on Rawls Kuberenetes pods, where it will accept statsd pushes on port 9125 and accept Prometheus scrapes on port 9102.

The sidecar actually does support forwarding to an existing statsd endpoint, but we don't want to send the HostedGraphite API key to the sidecar, so it isn't an option (the key is sent as part of the metric name itself, and none of our systems expect the literal metric name to have any secrets). 

Solution is to just send the stats twice, once to each endpoint. See https://github.com/broadinstitute/firecloud-develop/pull/2773 for what we can add to the Rawls config file to do this.

---

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes (none)
- [x] **Submitter**: Make sure Swagger is updated if API changes (none)
  - [x] **...and Orchestration's Swagger too!**
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli) (none)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks: (DDO ticket is out-of-band non-product work, we don't have these fields)
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary (no changes required)
- [x] **Submitter**: Database checks: (none)
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [x] **Submitter**: Update FISMA documentation if changes to: (none)
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
image

**Comment by jack-r-warren** [comment]
I'm just making fun of myself re the above, I have not nearly enough Scala or Rawls knowledge to understand what could be going on so I'm giving it one more run and I'll try to see if the test runs have any consistency

**Comment by jack-r-warren** [comment]
Okay, tons of different errors and actually the error that seems most consistent I didn't get at one point! https://fc-jenkins.dsp-techops.broadinstitute.org/job/rawls-fiab-test-runner/40748/console

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
jenkins retest

**Comment by jack-r-warren** [comment]
Okay the Jenkins tests actually passed. Thank goodness.

As for codecov, I don't think the original `statsd` block code I copied was tested either, and I'm not quite sure how to do so--running two mock statsd endpoints to actually receive the rawls connections seems like a huge and really brittle test to write (maybe I'm just thinking about it wrong)

**Review by jordansafer — APPROVED** [review]

**Pull request merged**
