### PR TITLE
[WOR-406] Update commons-io from 2.6 to 2.11.0

### PR DESCRIPTION
**Pull request by broadbot**
Updates [commons-io:commons-io](https://gitbox.apache.org/repos/asf?p=commons-io.git) from 2.6 to 2.11.0.

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/17235ca1e60ff61e35fe7b7cf51163a15ffc435d/docs/repo-specific-configuration.md) file.

Have a fantastic day writing Scala!

<details>
<summary>Files still referring to the old version number</summary>

The following files still refer to the old version number (2.6).
You might want to review and update them manually.
```
automation/project/Dependencies.scala
project/Dependencies.scala
project/Merging.scala
project/Settings.scala
```
</details>
<details>
<summary>Ignore future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "commons-io", artifactId = "commons-io" } ]
```
</details>

labels: library-update, old-version-remains, commit-count:1

### CODE REVIEW

**Comment by cahrens** [comment]
This is a pretty substantial change-- 2.6 was a few years ago. I think we would want to go through release notes on this one.

**Comment by marctalbott** [comment]
Release notes since 2.6 - https://commons.apache.org/proper/commons-io/changes-report.html

I looked into the `Files still referring to the old version number` that the PR description mentions. From what I can tell, those files are flagged because a different library's version also happens to include 2.6 (akka). No action necessary there.

**Review by aherbst-broad — APPROVED** [review]

**Review by cahrens — APPROVED** [review]
Code change looks good, haven't read through the change notes… trusting that you did @marctalbott

**Comment by marctalbott** [comment]
> Code change looks good, haven't read through the change notes… trusting that you did @marctalbott

@cahrens Yup everything there looks good, we are using this library sparingly and the only method we're using (`IOUtils.toInputStream(String, Charset)`) was not mentioned in the change notes

**Pull request merged**
