### PR TITLE
sbt assembly no longer runs test

### PR DESCRIPTION
**Pull request by helgridly**
This is a workaround for the issue Khalid is describing in #23 .

I've removed test from sbt assembly, and added an explicit call to sbt test in the docker install so it still runs on Junkins.
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [x] Tell  that the PR exists if he wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- [x] **LR**: Initial review by LR and others.
- [x] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [ ]  sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Squash commits, rebase if necessary
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Merge to develop 
- [ ] **Submitter**: Delete branch after merge
- [x] **Submitter**: Check configuration files in Jenkins in case they need changes
- [x] **Submitter**: Verify swagger UI on dev server still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by helgridly** [comment]
hey @dvoet i removed test from sbt assembly and put it back in docker install.sh

**Comment by abaumann** [comment]
looks good to me

**Comment by dvoet** [comment]
:+1: once tests

**Comment by helgridly** [comment]
aww crap. not my testfail but this is a nasty actor lookup issue.

**Comment by helgridly** [comment]
I'd like to merge this anyway as I can repro in develop. @dvoet thoughts? (I'm about to open a ticket.)

**Comment by dvoet** [comment]
merge it

**Pull request merged**
