### PR TITLE
Payoff some tech debt in tests

### PR DESCRIPTION
**Pull request by dmohs**
[This commit](https://github.com/broadinstitute/rawls/commit/8fccfdce4c03c1ff4837e5918e038b3e44b25f15) fixes a bug in our test data which made it unusable in some circumstances. Likely due to that problem, some tests create test data when they could be using the stock test data. This PR proves that to be true and provides an example of how to clean things up.

Found while working on [951](https://broadinstitute.atlassian.net/browse/GAWB-951).
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  - Acceptance criteria exists and is met
  - Note any changes to implementation from the description
  - Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Database checks:
  - If PR includes new or changed db queries, include the explain plans in the description
  - Make sure liquibase is updated if appropriate
  - If doing a migration, take a backup of the
    [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
    and
    [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
    DBs in Google Cloud Console
- [x] **Submitter**: Update FISMA documentation if changes to:
  - Authentication
  - Authorization
  - Encryption
  - Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell  that the PR exists if he wants to look at it **(apply requires_doge label)**
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- Review cycle:
  - LR reviews
  - Rest of team may comment on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH
  - Submitter updates documentation as needed
  - Submitter **reassigns to LR** for further feedback
- [x]  sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Review by dvoet — COMMENTED** [review]
So this now instantiates the entire test data set instead of only what it needs. Why is that better? What was the issue that was fixed?

**Comment by dmohs** [comment]
@dvoet This is better because it requires less code to accomplish the same task without significantly decreasing performance. The issue fixed is "more code than necessary to do something." I trust it is not necessary to enumerate the benefits.

More generally, isn't this the entire point of having test data? If not, why does it make sense in the previous test ("get a users own status") and not in this one?

**Review by dvoet — APPROVED** [review]
meh.. I don't really care:
pro - less code - but I have lower standards for test
con - slower test

I think people have been using the default test data because they are lazy (which I am a fan of) at the expense of slower tests and I would like to figure out how to fix that, i.e. how can we continue to be lazy but not have slower tests.

**Comment by MatthewBemis** [comment]
:+1:

**Comment by dmohs** [comment]
> how can we continue to be lazy but not have slower tests

+1

**Pull request merged**
