### PR TITLE
Add BigQuery user role to workspace writers

### PR DESCRIPTION
**Pull request by dmohs**
https://app.zenhub.com/workspace/o/databiosphere/saturn-ui/issues/202

Workspace creation documentation does not contain information about roles granted. It probably should, but that is a separate issue.

It's not clear what the best response is for when adding the roles fails. In this case, the workspace is nearly entirely usable, so it may not make sense to return an error code. On the other hand, an error did occur.

Idea for next iteration: Include status of role grants in workspace response along with a separate endpoint for re-granting the default roles. This would allow a user to monitor the grant status and take action if role granting fails after the initial creation of the workspace.

As far as I can tell, FISMA docs don't cover the specific permissions granted to users of the system, so no modifications are necessary.

Regarding testing, if we were to create the groups and ensure the roles were assigned, we'd have an expensive test that mostly tests Google's infrastructure. My preferred test would simply ensure that the workspace creation flow calls the necessary role-granting Google APIs. I can't see a reasonable way to do this in the current codebase.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [x] **Submitter**: Make sure Swagger is updated if API changes
  - [x] **...and Orchestration's Swagger too!**
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] Tell your tech lead (TL) that the PR exists if they want to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by jmthibault79** [comment]
How does this interact with AoU's requirements regarding Project Owners' granting and denial of this role to non-PO users?

**Comment by dmohs** [comment]
@bradtaylor Can you answer Joel's question above?

**Review by MatthewBemis — COMMENTED** [review]
code looks good. :+1: 

regarding testing: automation tests are failing because you forked the repo and apparently we can't build the rawls image in that case

in terms of adding an automation test, is there an endpoint you can call to list your bigquery roles? having a WS creator or writer call that endpoint to verify that this code worked wouldn't be too much work but i don't know if that endpoint exists

**Comment by dmohs** [comment]
Closing in favor of https://github.com/broadinstitute/rawls/pull/941 to work around bug in CI system.

**Pull request closed without merging**
