### PR TITLE
Data migration

### PR DESCRIPTION
**Pull request by dvoet**
we discovered that we are not saving the workspace group email addresses in the database so we had to implement something for data migration.

start by reading the scaladoc here https://github.com/broadinstitute/rawls/pull/277/files#diff-700dfec66337e1233bc8ff248a6dbe3dR14
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [x] Tell  that the PR exists if he wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- [x] **LR**: Initial review by LR and others.
- [x] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [x]  sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Squash commits, rebase if necessary
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Merge to develop 
- [x] **Submitter**: Delete branch after merge
- [ ] **Submitter**: Check configuration files in Jenkins in case they need changes
- [ ] **Submitter**: Verify swagger UI on dev server still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by helgridly** [comment]
I like that we maintain a record of which migrations have been done, and that we don't attempt to apply the same migration twice.

What I don't like is:
a) the migration becomes dead code as soon as it's run; and
b) we have to maintain said dead code as if we ever change interfaces (e.g. containerDAO changes or something)

I'd like a second opinion on this. How does this approach compare to e.g. standalone Scala scripts that we run on the database before starting Rawls and leave in the repo for historical purposes (but don't have to maintain)?

**Comment by helgridly** [comment]
paging @abaumann @jmthibault79 @MatthewBemis for thoughts

**Comment by dvoet** [comment]
perhaps we agree that if we find ourselves updating a migration we can evaluate whether or not it makes sense to do so and if we decide no then we strike the migration from the list and comment out the code but leave it for posterity.

one reason for deciding not to maintain it is we know that all of our databases have applied it.

Whatever it is, I feel strongly that it must be an automatic process.

**Comment by jmthibault79** [comment]
Still considering the overall approach.

Regardless of where the migration record lives, we should add detail.  If we take this PR's approach, I'd put this in the AddWorkspaceGroupEmailMigration code comments.

Some initial thoughts on things to include:
- Migration time (in the DB for this PR, that's good enough for me)
- Before and after versions, both in the "1.0" sense and commit hashes
- A detailed description of why the migration is necessary.  In this case, the reason some groups didn't have email addresses, and the reason that they are now required.

**Comment by dvoet** [comment]
The reason I like it in code is because we can reuse all the DAO functionality we have. Otherwise figuring out the graph traversal would be a PITA. Example, in AddWorkspaceGroupEmailMigration I need to get the groups associated to each workspace. I need to traverse from a workspace vertex to a map vertex to group vertex, remembering the label of the map to group edge and decode it (I think). All that is expressed nicely in a few lines here https://github.com/broadinstitute/rawls/pull/277/files#diff-503a6527fc346266810ddb8fb0bd5849R18

**Comment by dvoet** [comment]
@jmthibault79 I don't think a "1.0" style of versioning makes so much sense. I do like the idea of putting the commit hash in there. Just need to figure out how to get it. That also will be necessary for an api that displays the version of the app.

**Comment by jmthibault79** [comment]
I mean in the sense of FireCloud version numbers, like: this was the state of the DB for FC release 1.1

**Comment by dvoet** [comment]
@jmthibault79 I added jenkins build number, git hash and the version listed in build.sbt

**Comment by dvoet** [comment]
@helgridly @jmthibault79 any more opinions on this? Seems like the cons with this approach are that it creates dead code and we need to maintain that dead code. The pro is that it is easier to write the migrations. In a scripted approach the cons are that we would need an extra step somewhere to launch the migration and that it is hard to write migrations without access to all the GraphDAOs that we have. The pro is that even though the migration becomes dead code, it is not deployed code and does not need to be maintained.

I think we can mitigate the cons in the method proposed in this PR but not as easily in the scripted approach.

**Comment by helgridly** [comment]
I think this is the best we can realistically do. :+1:

**Comment by dvoet** [comment]
@helgridly I am taking that as a sign off

**Comment by helgridly** [comment]
It is one, I just forgot to click the boxes

**Comment by jmthibault79** [comment]
:+1:

**Pull request merged**
