### PR TITLE
PROD-750: Revert "Add heartbeat and liveness checks..."

### PR DESCRIPTION
**Pull request by cjllanwarne**
This reverts commit 9f848346269e7f7f654f78d3cb227e4b28bfbab2 to test whether it resolves test deadlock issues.

### CODE REVIEW

**Comment by cjllanwarne** [comment]
jenkins retest

**Comment by cjllanwarne** [comment]
jenkins retest

**Comment by cjllanwarne** [comment]
jenkins retest

**Comment by jgainerdewar** [comment]
jenkins retest

**Review by jgainerdewar — APPROVED** [review]

**Review by MatthewBemis — APPROVED** [review]

**Comment by jgainerdewar** [comment]
I did a manual `rawls-build` run of this branch that included tests, and passed all tests. It then failed to push to Artifactory, but that seems unrelated

https://fc-jenkins.dsp-techops.broadinstitute.org/job/rawls-build/7469/consoleFull

The equivalent manual run of https://github.com/broadinstitute/rawls/pull/2138 failed with the same `SubmissionMonitorSpec` error we have been seeing on all with-tests Rawls builds:

https://fc-jenkins.dsp-techops.broadinstitute.org/job/rawls-build/7467/

Conclusion is that this change is causing the error, we are reverting it.

**Pull request merged**
