### PR TITLE
[WOR-552] Update rawls-model dependency with an official version

### PR DESCRIPTION
**Pull request by ghost**
Ticket: https://broadworkbench.atlassian.net/browse/WOR-552
followed the instructions in https://github.com/broadinstitute/rawls#publish-rawls-model
<Put notes here to help reviewer understand this PR>
- update rawls-model dependency to the most recently published version 
---

**PR checklist**

- [ ] Include the JIRA issue number in the PR description and title
- [ ] Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] If you changed anything in `model/`, then you should [publish a new official `rawls-model`](https://github.com/broadinstitute/rawls/blob/develop/README.md#publish-rawls-model) and update `rawls-model` in [Orchestration's dependencies](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/project/Dependencies.scala).
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green, including CI tests
- [ ] **Squash commits and merge** to develop (branches are automatically deleted after merging)
- [ ] Inform other teams of any substantial changes via Slack and/or email

### CODE REVIEW

**Review by ehigham — APPROVED** [review]

**Review by cahrens — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
jenkins retest

**Review by aherbst-broad — APPROVED** [review]

**Comment by ghost** [comment]
jenkins retest

**Comment by ghost** [comment]
jenkins retest

**Comment by ghost** [comment]
jenkins retest

**Pull request merged**
