### PR TITLE
upgrade java libs to cromwell 34

### PR DESCRIPTION
**Pull request by davidangb**
adopt the cromwell 34 library.

this is untested beyond unit/automation tests.

### CODE REVIEW

**Review by jmthibault79 — APPROVED** [review]
Confirmed hash = 34 release tag

**Comment by rtitle** [comment]
Make sure this is updated to the 34-hotfix hash.

**Comment by jmthibault79** [comment]
+ Agora too

**Comment by davidangb** [comment]
3 UI/Selenium failures and 1 rawls-test failure at https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8107/:
ui tests:
```
[info] *** 3 TESTS FAILED ***
[error] Failed: Total 124, Failed 3, Errors 0, Passed 121, Ignored 5
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.security.AuthDomainMultiGroupsSpec
```
rawls tests:
```
[info] *** 1 TEST FAILED ***
[error] Failed: Total 10, Failed 1, Errors 0, Passed 9
[error] Failed tests:
[error] 	org.broadinstitute.dsde.test.api.RawlsApiSpec

[info] - should retrieve sub-workflow metadata from Cromwell *** FAILED ***
[info]   The code passed to eventually never returned normally. Attempted 23 times over 5.16232311685 minutes. Last failure message: Submission gpalloc-qa-master-6fyizff/rawls-subworkflow-metadata cc123c9c-7934-40a2-aa69-ecb56f8cf073/55cc4dfa-bf20-4ab9-a7be-f8bb238d287b: "Abort[ing]" was not equal to "Abort[ed]". (RawlsApiSpec.scala:207)
```
the rawls test is suspicious.

**Comment by davidangb** [comment]
jenkins retest

**Comment by davidangb** [comment]
second automation run passed rawls tests, but has UI failures at https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8117/:
```
[info] *** 3 TESTS FAILED ***
[error] Failed: Total 124, Failed 3, Errors 0, Passed 121, Ignored 5
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.analysis.MethodLaunchSpec
[error] 	org.broadinstitute.dsde.firecloud.test.security.AuthDomainMultiGroupsSpec
[error] 	org.broadinstitute.dsde.firecloud.test.analysis.MethodRedactedSpec
```

**Comment by davidangb** [comment]
* `MethodRedactedSpec` passed in a manual run: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8129/
* `MethodLaunchSpec` passed in a manual run: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/8127/
* `AuthDomainMultiGroupsSpec` passed in a manual run: https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Pipelines/job/swatomation-pipeline/8130/

**Pull request merged**
