### PR TITLE
remove hamm [no ticket; risk: low]

### PR DESCRIPTION
**Pull request by davidangb**
[Hamm](https://github.com/DataBiosphere/hamm) is an abandoned cost-tracking effort that is not in use. But, Rawls contains code to upload Hamm cost info to a bucket, where Hamm would have read it if Hamm was active. This Rawls code is chatty in the logs and pollutes the codebase. Let's remove it.

-----

remaining TODOs, for which I will file follow-on Jira tickets:
* [ ] remove Hamm's bucket and its contents, after confirming we don't want that data
* [ ] remove Hamm values from conf files

### CODE REVIEW

**Review by kshakir — APPROVED** [review]
No clue what this was... so uh LGTM

**Review by aednichols — CHANGES_REQUESTED** [review]
I would prefer to see a "why?" in the PR summary for change tracking purposes

**Comment by davidangb** [comment]
@aednichols I updated the PR summary, PTAL?

**Review by aednichols — APPROVED** [review]
TYVM LGTM 👍

**Review by MatthewBemis — APPROVED** [review]

**Pull request merged**
