### PR TITLE
Enable submission timeouts to allow GAWB-605 analysis

### PR DESCRIPTION
**Pull request by jmthibault79**
Follow-on to #409 which was an incomplete solution.  This PR changes the overall submission timeout to match those of the individual submissions.  Resolves GAWB-605.
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Make sure liquibase is updated if appropriate
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [x] Tell  that the PR exists if he wants to look at it **(apply requires_doge label)**
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- [x] **LR**: Initial review by LR and others.
- [x] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [x]  sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Squash commits, rebase if necessary
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Merge to develop 
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: Check configuration files in Jenkins in case they need changes
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by rushtong** [comment]
Generic question - is this something we need on other `*Create` service calls or is it sufficient for just this one?

**Comment by rushtong** [comment]
👍 - back to you @jmthibault79

**Comment by dvoet** [comment]
why is this required to fix GAWB-605? Why was #409 incomplete

**Comment by jmthibault79** [comment]
Greg: this is intentionally minimal, to only change Submission creation behavior.

Doug: Local is so slow that sometimes submission creation times out in the expression evaluation stage, before submitWorkflow is even called.  It doesn't necessarily follow that these two should have the _same_ timeout value, but I don't think we need that precision if we're just trying to make sure both are "long enough"

**Comment by dvoet** [comment]
👍

**Pull request merged**
