### PR TITLE
[WOR-686] Remove check against the alpha feature group when pulling billing profiles

### PR DESCRIPTION
**Pull request by aherbst-broad**
[Ticket](https://broadworkbench.atlassian.net/browse/WOR-686)
We were gating the availability of billing profiles by membership in the alpha-azure-feature-group Sam group. We need to remove this check for prod availability.

---

**PR checklist**

- [ ] Include the JIRA issue number in the PR description and title
- [ ] Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] If you changed anything in `model/`, then you should [publish a new official `rawls-model`](https://github.com/broadinstitute/rawls/blob/develop/README.md#publish-rawls-model) and update `rawls-model` in [Orchestration's dependencies](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/project/Dependencies.scala).
- [ ] Get two thumbsworth of PR review
- [ ] Verify all tests go green, including CI tests
- [ ] **Squash commits and merge** to develop (branches are automatically deleted after merging)
- [ ] Inform other teams of any substantial changes via Slack and/or email

### CODE REVIEW

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Review by cahrens — APPROVED** [review]

**Review by marctalbott — APPROVED** [review]

**Comment by aherbst-broad** [comment]
jenkins retest

**Comment by aherbst-broad** [comment]
jenkins retest

**Pull request merged**
