### PR TITLE
downgrade akka-http to 10.1.2 to accomodate New relic metrics

### PR DESCRIPTION
**Pull request by Qi77Qi**
Once @hjfbynara 's PR for upgrading new relic agent version is merged into firecloud-develop, this should make NR metrics work again for rawls

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [x] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by breilly2** [comment]
Check what version this resolves to. I suspect that you'll actually get 10.1.3 as a transitive dependency of cromwell-wom.

**Comment by Qi77Qi** [comment]
@breilly2  yea, you're right...10.1.2 is evicted. I'll see if 10.1.3 works with NR

**Comment by Qi77Qi** [comment]
@breilly2  I checked 10.1.3 locally, it works with NR just fine

**Comment by breilly2** [comment]
Okay. My concern is still that rawls is not in control of this dependency. Rawls is in trouble If cromwell-wom upgrades to 10.1.5.

**Review by breilly2 — APPROVED** [review]
Approved with reservations. Everything about this (the transitive dependency, the security vulnerabilities, and the issues with new relic) is way too fragile.

**Comment by Qi77Qi** [comment]
@breilly2 agree, I don't think this is anything permanent, but just a temporary fix for NR metrics

**Comment by rtitle** [comment]
Admittedly I haven't tried it, but could we add:
```
 exclude("com.typesafe.akka", "akka-http_2.12"))
```
to the `cromwellWdl` dependency to remove the transitive akka-http dependency?

**Review by rtitle — APPROVED** [review]

**Review by dvoet — APPROVED** [review]

**Pull request merged**
