### PR TITLE
Consider Google group creation a success if it already exists

### PR DESCRIPTION
**Pull request by dmohs**
Found while setting up user and workspaces for GAWB-358.
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Make sure liquibase is updated if appropriate
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [ ] Tell  that the PR exists if he wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
- [ ] **LR**: Initial review by LR and others.
- [ ] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [ ]  sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Squash commits, rebase if necessary
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Merge to develop 
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: Check configuration files in Jenkins in case they need changes
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by helgridly** [comment]
Is there a ticket for this? What issue does it fix? Where's it prioritised? Are we tracking this work?

**Comment by dmohs** [comment]
Ticket added to description. Creating a separate ticket seems like overkill, but I will do that if desired.

**Comment by helgridly** [comment]
Why should we consider it a success rather than passing the 409 Conflict on to the user? (I don't know the answer; there's arguments both ways.) If we do this, it's an API change, so it potentially affects users. This needs to be documented in Swagger, which you ticked off in the checklist but didn't do. Naughty!

**Comment by abaumann** [comment]
I'm not sure we want this, at least how it's been written.  This makes it so createGoogleGroup just handles 409s and returns the group the user _tries_ to create, however if it already exists it will have other users in it, not the empty user list/group list (Set.empty[RawlsUserRef], Set.empty[RawlsGroupRef]).  

We do handle conflict for existing rawls group in UserService / createGroup(...), so this at least won't violate existing RawlsGroups.  I think the case your code covers is only if we cleared a db and a group already existed.  In this case what your code would do is overwrite that RawlsGroup with an empty group, is that what we want?  I also think what it might do is give us an empty RawlsGroup but a Google group that still has members.  Maybe what you want instead is to have the RawlsGroup sync itself with an existing Google group when it finds it already exists?

**Comment by jmthibault79** [comment]
I haven't been following this closely, but https://github.com/broadinstitute/rawls/pull/272 also deals with group-sync so may be helpful to look at.

**Comment by dvoet** [comment]
👎 we definitely don't want this. If the group exists the membership is likely out of sync. In the cases where we don't care that the group already exists we should handle it at a higher level.

**Pull request closed without merging**
