### PR TITLE
AuthDomainMultiGroupApiSpec: retry failed check with eventually

### PR DESCRIPTION
**Pull request by aweng98**
[QA-565](https://broadworkbench.atlassian.net/browse/QA-565)

### CODE REVIEW

**Comment by helgridly** [comment]
this implies that either:
- we don't wait for the HTTP request to /clone to finish before moving on to the next line, which i think would be a testing antipattern; or
- we do wait for the HTTP request to complete, but that it's doing some things asynchronously afterwards. in which case: is this documented and clear?

**Comment by aweng98** [comment]
@helgridly I feel answer is in your second point. Test failure with error `"[NO ACCESS]" was not equal to "[WRITER]"` is intermittent in Alpha but not in dev. I don't know any documentation about this, but Sam does cache and cache time is a minute long (TTL). I used 150 seconds to be "very generously". Do you feel this is a real product issue, not a test issue?

**Comment by helgridly** [comment]
I'm gonna drag in @dvoet here. I don't know why the cache would kick in on the clone of a fresh workspace -- I imagine there wouldn't be a value in the cache at all, but I might be missing something.

**Comment by aweng98** [comment]
Use `eventually` only for failed check for now.

**Comment by aweng98** [comment]
jenkins retest

**Comment by aweng98** [comment]
@gpolumbo-broad any thoughts?

**Review by gdlex4015 — APPROVED** [review]

**Comment by dvoet** [comment]
@helgridly the thing that sam caches is the list of groups the user is a member of so a cache miss is possible the way this test is structured.

**Review by dvoet — APPROVED** [review]

**Pull request merged**
