### PR TITLE
getWorkspaceOwners via graph lookup

### PR DESCRIPTION
**Pull request by MatthewBemis**
https://broadinstitute.atlassian.net/browse/DSDEEPB-1799
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [ ] Tell  that the PR exists if he wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
- [ ] **LR**: Initial review by LR and others.
- [ ] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [ ]  sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Squash commits, rebase if necessary
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Merge to develop 
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: Check configuration files in Jenkins in case they need changes
- [ ] **Submitter**: Verify swagger UI on dev server still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by dvoet** [comment]
sorry Matt, back to the drawing board: I don't think there should be individual DAO methods for this stuff. There should be a loadGroup method that uses the reflection deserialization to get a RawlsGroup. Then the caller can do whatever they want with the object.

I also don't think this addresses the story. You made these new functions but nobody is calling them so you did not actually "Update getOwners to query the graph instead of Google"

**Comment by MatthewBemis** [comment]
For loading a group, is something like this more appropriate?

in GraphAuthDAO:

```
  def loadGroup(groupName: String, txn: RawlsTransaction): RawlsGroup = txn withGraph { db =>
    getGroupVertex(db, groupName) match {
      case None => throw new RawlsException(s"Cannot load group ${groupName}")
      case Some(v) =>
        loadObject[RawlsGroup](v)
    }
  }
```

and then from that RawlsGroup, I'm able to load the subGroups and the users. Would the method to do that not also be in GraphAuthDAO?

**Comment by dvoet** [comment]
yes, that looks fine. Why do you need more auth dao methods? I am having trouble following without seeing this stuff in action. What will the new list workspaces end point look like?

**Comment by MatthewBemis** [comment]
I needed the additional dao methods to get the users/subgroups out of the RawlsGroup. I also wanted them in there because it made it easy to construct a WorkspaceACL map- just load each group and then grab each user ID and group name for each access level. I'm not sure what the list workspaces endpoint will look like- that's a different story that hasn't been picked up.

**Comment by dvoet** [comment]
The list workspace api should remain the same, we are just changing the underlying implementation... getOwners gets the same stuff just from a different place. That is what I read this story to be.

**Comment by MatthewBemis** [comment]
to be covered in a followup PR

**Pull request closed without merging**
