### PR TITLE
Travis should use same Scala version as sbt build [no ticket; risk: no]

### PR DESCRIPTION
**Pull request by davidangb**
See https://github.com/broadinstitute/rawls/blob/develop/project/Settings.scala#L54 ... Travis should use the same version.

### CODE REVIEW

**Comment by davidangb** [comment]
jenkins had fiab-start failures, but ... I'm not going to re-run. This is a Travis-only change.

**Comment by davidangb** [comment]
jenkins retest

**Comment by davidangb** [comment]
yeah, I keep getting fiab failures but still, this is just a Travis change.

**Review by zarsky-broad — APPROVED** [review]
Makes sense and looks good, scala version in the travis builds is indeed changed to 2.12.10!

**Pull request merged**
