### PR TITLE
Add deadlock.md file to git

### PR DESCRIPTION
**Pull request by rtitle**
Following @dmohs suggestion about adding technical docs to git. No JIRA.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by rtitle** [comment]
@helgridly what are your thoughts about adding these types of docs to git? [firecloud-ui](https://github.com/broadinstitute/firecloud-ui/tree/develop/doc/2017) does similar.

**Comment by helgridly** [comment]
I like these documents but not in git. We have a few similar-ish things in Confluence: https://broadinstitute.atlassian.net/wiki/spaces/GAWB/pages . I'd suggest a subpage in either [Developer HOWTOs](https://broadinstitute.atlassian.net/wiki/spaces/GAWB/pages/33095753/Developer+HOWTOs) or the [Cross Team Tech Talks](https://broadinstitute.atlassian.net/wiki/spaces/GAWB/pages/113030384/Cross-Team+Tech+Talks) page.

**Comment by helgridly** [comment]
Maybe chat with Kendra to facilitate discussion if teams are beginning to diverge on where documents like this should live.

**Comment by rtitle** [comment]
OK, I can port it to confluence

**Comment by rtitle** [comment]
https://broadinstitute.atlassian.net/wiki/spaces/GAWB/pages/116175886/Case+Study+Debugging+Database+Deadlocks

**Comment by dmohs** [comment]
@helgridly @rtitle I think that a developer who is working on Rawls is likely to have this repo cloned. If that is true, they are likely to stumble upon useful engineering documentation contained within a `doc` folder here. I think it is much less likely they will know to search in Confluence. Do you disagree?

**Comment by helgridly** [comment]
@dmohs This is a philosophical question about where developer focused documentation for Workbench should live. Currently, it lives in Confluence. So new documentation should go there. If you'd like to propose it lives somewhere else, a GitHub PR comment thread isn't the correct place for that proposal - it's a team decision and should be raised either on our internal email list or cross-team tech talk. Please raise this discussion there, not here.

**Comment by dmohs** [comment]
@helgridly Fair point. Good call.

**Pull request closed without merging**
