### PR TITLE
Ah gawb 2643: fill in all_attribute_values for entity on patch

### PR DESCRIPTION
**Pull request by ahaessly**
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [x] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] Tell your tech lead (TL) that the PR exists if they want to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by ahaessly** [comment]
new sql statement in patch:

[DEBUG] [22:39:14.738] [slick.db-13] slick.jdbc.JdbcBackend.statement - Preparing statement: update `ENTITY` set `id` = ?, `name` = ?, `entity_type` = ?, `workspace_id` = ?, `record_version` = ?, `all_attribute_values` = ?, `deleted` = ?, `deleted_date` = ? where (`ENTITY`.`id` = 1) and (`ENTITY`.`record_version` = 0)

**Review by dvoet — APPROVED** [review]

**Review by davidangb — APPROVED** [review]
:+1: code looks good; did not test.

**Review by aednichols — APPROVED** [review]
Looks good - neat fix - maybe you should describe your debugging process at the next XTTT.

For my own learning, are the branches `ah-gawb-2643-fiab` and `ah-gawb-2643-migrate` part of some special process or just experimentation?

**Comment by ahaessly** [comment]
i didn't really use the migrate branch - i thought i needed a branch without the fix so i could reproduce the problem then run the migration script. but i was able to do this using a clone of the dev database. the fiab branch was a branch with the sql logging turned on so i could capture the sql that was generated for the fix. didn't want to accidentally merge that.

**Pull request merged**
