### PR TITLE
update mysql-connector-java [AJ-273]

### PR DESCRIPTION
**Pull request by davidangb**
Updates the version of `mysql-connector-java`, with corresponding syntax changes. This addresses proactive security vulnerability scan findings.

Note that AJ-273 also mentions `jersey-core-common`, I will handle that separately to keep PRs concise.

This PR uses connector version 8.0.28 against our 5.6 server. There was a question about compatibility; https://dev.mysql.com/downloads/connector/j/ states "MySQL Connector/J 8.0 is highly recommended for use with MySQL Server 8.0, 5.7 and 5.6. Please upgrade to MySQL Connector/J 8.0." 

The connector update required Scala syntax changes regarding exceptions. I used https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-exceptions-changes.html to guide the syntax changes.

### CODE REVIEW

**Comment by davidangb** [comment]
swatomation seemed hung and I aborted it. Hopefully this is a quirk/transient. Jenkins retest.

**Comment by davidangb** [comment]
Jenkins retest?

**Comment by davidangb** [comment]
passed on `eclipse-temurin-11.0.13_1.5.5_2.12.15`, let's try a minor-version upgrade to `graalvm-ce-21.3.0-java11_1.5.5_2.12.15`

**Comment by davidangb** [comment]
The [swat run](https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/60362/) passed all tests but had one error during cleanup:
```
ErrorReport(WorkbenchLibs.CleanUp,Test passed but cleanup failed: {"causes":[],"message":"HTTP error calling URI https://sam-fiab.dsde-qa.broadinstitute.org/api/resources/v2/billing-project/gpalloc-qa-master-6repyix/children. Response: {\"causes\":[],\"message\":\"Resource billing-project/gpalloc-qa-master-6repyix not found\",\"source\":\"sam\"
```
I'm considering that a passing run.

**Review by jordansafer — APPROVED** [review]

**Comment by davidangb** [comment]
jenkins retest

**Comment by davidangb** [comment]
jenkins retest

**Pull request merged**
