### PR TITLE
CA-463 static perimeter projects

### PR DESCRIPTION
**Pull request by gpolumbo-broad**
https://broadworkbench.atlassian.net/browse/CA-463

Must be merged AFTER:  https://github.com/broadinstitute/firecloud-develop/pull/1789

### CODE REVIEW

**Review by marctalbott — APPROVED** [review]

**Comment by marctalbott** [comment]
Have you tested this?

**Review by jmthibault79 — APPROVED** [review]
This looks correct to me: adding the static SP projects to the SP but not the Folder.

**Comment by gpolumbo-broad** [comment]
jenkins retest this again and bring me a cup of tea.  Earl Grey.  Hot.

**Comment by gpolumbo-broad** [comment]
jenkins retest this again but with the correct version of firecloud-develop if it's not too much trouble for ya

**Pull request merged**
