### PR TITLE
These tests were no longer valid after an API change a while back

### PR DESCRIPTION
**Pull request by jmthibault79**
No JIRA.  Found this while working on other stuff.

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Check that the **Product Owner** has signed off on any user-facing changes
- [ ] **Submitter**: Make sure Swagger is updated if API changes
  - [ ] **...and Orchestration's Swagger too!**
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Database checks:
  * If PR includes new or changed db queries, include the explain plans in the description
  * Make sure liquibase is updated if appropriate
  * If doing a migration, take a backup of the
  [dev](https://console.cloud.google.com/sql/instances/terraform-qfarbdq3lrexxck5htofjs5z6m/backups?project=broad-dsde-dev&organizationId=548622027621)
  and
  [alpha](https://console.cloud.google.com/sql/instances/terraform-r4caezzc35c4tb7pgdhwkmme4y/backups?project=broad-dsde-alpha&organizationId=548622027621)
  DBs in Google Cloud Console
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] Tell your tech lead (TL) that the PR exists if they want to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by jmthibault79** [comment]
We missed these because we were testing for 404s.  Yep, these routes didn't exist: 404.

**Review by helgridly — APPROVED** [review]

**Comment by breilly2** [comment]
I haven't looked closely enough yet to tell whether or not the changes are correct. However it bothers me that these tests are so prone to false success which is a really bad thing.

I've never before found use for a spy but it's the only way I can think of to verify that the rawls code is actually being called and therefore that the 404 is being returned intentionally. Would it be possible to add a spy here? Not sure if there's any support built into anything we're already using but I know mockito supports spies (just not sure how well it would work with scala).

**Comment by dvoet** [comment]
perhaps a best practice for this case (404 testing) is to have the same unit test do both positive and negative tests.

**Comment by breilly2** [comment]
As long as there is shared code in the tests for constructing the endpoint URLs used, there can still be separate positive and negative tests. I think that's a good approach and far less effort than figuring out how to instrument spies.

**Comment by jmthibault79** [comment]
I agree that we need a more general solution for this.  Thanks for your suggestions.  I added them to https://broadinstitute.atlassian.net/browse/GAWB-2327

**Pull request merged**
